const types = {
  DISMISS_TOAST: "DISMISS_TOAST",
  SHOW_TOAST: "SHOW_TOAST",
  SET_GATEWAYS: "SET_GATEWAYS",
  ADD_NEW_GATEWAY: "ADD_NEW_GATEWAY",
  DELETE_GATEWAY: "DELETE_GATEWAY",
  ADD_NEW_DEVICE: "ADD_NEW_DEVICE",
  DELETE_DEVICE: "DELETE_DEVICE",
  SET_IS_LOADING: "SET_IS_LOADING",
};
export default types;
